- hosts: localhost
  gather_facts: no
  vars_files:
        - cred.yml
  tasks:
    - name: Running EC2 Role
      include_role:
        name: ec2-instance

- hosts: ec2_haproxy
  gather_facts: no
  tasks:
    - name: RUNNING HAPROXY
      include_role:
        name: haproxy

- hosts: ec2_server
  gather_facts: no
  tasks:
    - name: RUNNING WEBSERVER
      include_role:
        name: webserver

